# Generated by Django 5.2.7 on 2025-11-10 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_hotelvendor_business_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hoteluser",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hotelvendor",
            options={},
        ),
        migrations.AlterModelTable(
            name="hoteluser",
            table="hotel_users",
        ),
        migrations.AlterModelTable(
            name="hotelvendor",
            table="hotel_vendors",
        ),
    ]
