# Generated by Django 5.2.7 on 2025-11-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_hoteluser_options_alter_hotelvendor_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hoteluser",
            name="email_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hotelvendor",
            name="email_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
